name: Rest Assured API Automation

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

  # Runs every day at 10:00 AM IST (04:30 UTC)
  schedule:
    - cron: "*/5 * * * *"

jobs:
  api-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Build and Execute TestNG Suite
        run: mvn clean test -Dsurefire.suiteXmlFiles=testng.xml

      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-report
          path: target/surefire-reports/

      - name: Upload Cucumber Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: |
            target/cucumber-reports.html
            target/cucumber-report.json

      - name: Send Email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true

          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}

          subject: "Rest Assured API Automation Execution Report"

          to: ananth021996@gmail.com,abhiramik.bca@gmail.com

          # Optional
          # cc: manager@gmail.com
          # bcc: qa.team@gmail.com

          from: GitHub Actions

          body: |
            Hello,

            The Rest Assured API Automation execution has completed.

            Trigger: ${{ github.event_name }}

            Repository: ${{ github.repository }}

            Branch: ${{ github.ref_name }}

            Commit: ${{ github.sha }}

            Workflow: ${{ github.workflow }}

            Job Status: ${{ job.status }}

            Regards,
            Harshitha Kanishk

          attachments: |
            target/surefire-reports/emailable-report.html
            target/cucumber-reports.html
